name: CD/CD for the ml-pipeline that builds all the pipeline modules and pushes them to the private PyPI registry. From where Airflow will install the latest versions and use them in the next run.

on:
  push:
    paths-ignore:
      - 'app-api/'
      - 'app-frontend/'
      - '**/*.yml'
      - '**/*.md'
    branches: [ "main" ]
    
env:
  CLOUDSDK_CORE_PROJECT: '${{ vars.CLOUDSDK_CORE_PROJECT }}'
  USER: '${{ vars.USER }}'
  INSTANCE_NAME: '${{ vars.ML_PIPELINE_INSTANCE_NAME }}'
  ZONE: '${{ vars.ZONE }}'

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          project_id: '${{ env.CLOUDSDK_CORE_PROJECT }}'
          user: '${{ env.USER }}'
          instance_name: '${{ env.INSTANCE_NAME }}'
          zone: '${{ env.ZONE }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: >
            cd ~/energy-forecasting && 
            git pull && 
            sh deploy/ml-pipeline.sh
